monolog:
    handlers:
        logfile:
            type:  rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 14
        main:
            type: fingers_crossed
            level: debug
            channels: ["!event"]
            handler: elklogger
            action_level: error
            excluded_http_codes: [404, 405]
            buffer_size: 50
        elklogger:
            type: service
            id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
