version: "3"

server:
  command: "php public/index.php"
  relay: pipes
  access_logs: true
  env:
    - APP_RUNTIME: FluffyDiscord\RoadRunnerBundle\Runtime\Runtime

#otel:
#  insecure: true
#  compress: false
#  client: http
#  exporter: otlp
#  service_name: rr # your app name
#  service_version: 1.0.0 # your app version
#  endpoint: collector:4318

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080
  middleware: ["http_metrics" ]
  pool:
    max_jobs: 100 # Maximal count of worker executions. Zero (or nothing) means no limit.
    supervisor:
      max_worker_memory: 100 # Maximal worker memory usage in megabytes (soft limit). Zero means no limit.

temporal:
  address: "temporal:7233"
  activities:
    command: "php bin/console temporal:workflow:runtime"
    num_workers: 10
    max_jobs: 100
    supervisor:
      max_worker_memory: 100
  metrics:
    address: 0.0.0.0:9091

service:
  unit_runner_jobs:
    command: "php bin/console app:service:start unit_runner_jobs"
    process_num: 1
    timeout_stop_sec: 10
    exec_timeout: 0s
    remain_after_exit: true
    service_name_in_log: false
    restart_sec: 1

centrifuge:
  proxy_address: "tcp://0.0.0.0:30000"

metrics:
  address: 0.0.0.0:2112

amqp:
  addr: amqp://asd:asd@rabbit:5672

jobs:
  num_pollers: 24
  timeout: 5
  pool:
    max_jobs: 200
    num_workers: 4
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: [ "ochered_unitov", "prozess_obnovlenie_koda_posle_zapuska", "prozess_udaleniya_unita_posle_zapuska", "sobitiya_iz_hranilisha" ]
  pipelines:
    ochered_unitov:
      driver: amqp
      config:
        queue: ochered_unitov
        routing_key: ochered_unitov
        priority: 1
        prefetch: 10
        exchange: default
    prozess_obnovlenie_koda_posle_zapuska:
      driver: amqp
      config:
        queue: prozess_obnovlenie_koda_posle_zapuska
        routing_key: prozess_obnovlenie_koda_posle_zapuska
        priority: 2
        prefetch: 10
        exchange: default
    prozess_udaleniya_unita_posle_zapuska:
      driver: amqp
      config:
        queue: prozess_udaleniya_unita_posle_zapuska
        routing_key: prozess_udaleniya_unita_posle_zapuska
        priority: 3
        prefetch: 10
        exchange: default
    sobitiya_iz_hranilisha:
      driver: amqp
      config:
        queue: sobitiya_iz_hranilisha
        routing_key: sobitiya_iz_hranilisha
        priority: 4
        prefetch: 10
        exchange: default
