version: "3"

server:
  command: "php public/index.php"
  access_logs: true
  env:
    - APP_RUNTIME: FluffyDiscord\RoadRunnerBundle\Runtime\Runtime

#otel:
#  insecure: true
#  compress: false
#  client: http
#  exporter: otlp
#  service_name: rr # your app name
#  service_version: 1.0.0 # your app version
#  endpoint: collector:4318

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080
  middleware: ["http_metrics" ]
  pool:
    max_jobs: 100 # Maximal count of worker executions. Zero (or nothing) means no limit.
    supervisor:
      max_worker_memory: 100 # Maximal worker memory usage in megabytes (soft limit). Zero means no limit.

temporal:
  address: "temporal:7233"
  activities:
    command: "php bin/console temporal:workflow:runtime"
    num_workers: 10
    max_jobs: 100
    supervisor:
      max_worker_memory: 100
  metrics:
    address: 0.0.0.0:9091

service:
  ochered_unitov:
    command: "php bin/console app:service:start ochered_unitov"
    process_num: 1
    timeout_stop_sec: 10
    exec_timeout: 0s
    remain_after_exit: true
    service_name_in_log: false
    restart_sec: 1

metrics:
  address: 0.0.0.0:2112

jobs:
  num_pollers: 64
  timeout: 5
  pipeline_size: 100000

  pool:
    num_workers: 10
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: [ "local" ]
  pipelines:
    local:
      driver: memory
      config:
        priority: 10
        prefetch: 10000
