version: "3"

server:
  command: "php public/index.php"
  env:
      APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4

temporal:
  address: "host.docker.internal:7233"
  activities:
    command: "php bin/console temporal:workflow:runtime"
    num_workers: 10

service:
  ochered_unitov:
    command: "php bin/console app:service:start ochered_unitov"
    process_num: 1
    timeout_stop_sec: 10
    exec_timeout: 0s
    remain_after_exit: true
    service_name_in_log: false
    restart_sec: 1

