services:
  web:
    build:
      context: ./
      args:
        - CURRENT_USER_ID=${UID}
        - CURRENT_USER_GROUP=${GID}
    restart: always
    ports:
      - '${UNITMAN_API_PORT}:8080'
      - 2112:2112
      - 30000:30000
    user: root
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    volumes:
      - ./.docker/php/settings.ini:/usr/local/etc/php/php.ini

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.0
    restart: always
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    #volumes:
    # - ./var/volume/elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:7.14.0
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - ${KIBANA_PORT}:5601
    #volumes:
    # - ./var/volume/kibana_data:/usr/share/kibana/data

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./var/volume/pgdata:/var/lib/postgresql/data

  unitman-proxy:
    image: nginx
    restart: always
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/html/index.html:/usr/share/nginx/html/index.html
    ports:
      - '8087:80'

  beanstalk:
    container_name: beanstalk
    image: touchify/beanstalkd
    hostname: beanstalk
    restart: always
    environment:
      BEANSTALKD_VERBOSE: 1
    volumes:
      - ./var/volume/beanstalk:/var/cache/beanstalkd

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./.docker/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.25.0
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    ports:
      - 7233:7233

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.25.0-tctl-1.18.1-cli-1.0.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.26.2
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_UI_ENABLED=true
    ports:
      - 8088:8080

  postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - 5433:5432
    volumes:
      - ./var/volume/pgdata_temporal:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./var/volume/redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
