services:
  postgresql:
    extends:
      file: common-services.yml
      service: postgresql

  temporal:
    extends:
      file: common-services.yml
      service: temporal

  temporal-admin-tools:
    extends:
      file: common-services.yml
      service: temporal-admin-tools

  temporal-create-namespace:
    extends:
      file: common-services.yml
      service: temporal-create-namespace

  temporal-ui:
    extends:
      file: common-services.yml
      service: temporal-ui

  buggregator:
    extends:
      file: common-services.yml
      service: buggregator

  web:
    extends:
      file: common-services.yml
      service: web
    depends_on:
      - temporal
      - beanstalk
      - centrifugo
      - postgres
      - buggregator
    environment:
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_ENABLE_CLI=1
      - PHP_ERROR_REPORTING="E_ALL"
      - PHP_DISPLAY_ERRORS=On
    volumes:
      - ./config/jwt:/home/containeruser/www/config/jwt

  #elasticsearch:
  #  extends:
  #    file: common-services.yml
  #    service: elasticsearch

  #kibana:
  #  extends:
  #    file: common-services.yml
  #    service: kibana

  postgres:
    extends:
      file: common-services.yml
      service: postgres

  unitman-proxy:
    extends:
      file: common-services.yml
      service: unitman-proxy

  unitman-front:
    image: asdozzz/unitman-front:0.0.3
    environment:
      API_HOST: http://localhost:${UNITMAN_API_PORT}/api
      CENTRIFUGE_HOST: ws://localhost:${UNITMAN_CENTRIFUGO_PORT}/connection/websocket
    ports:
      - ${UNITMAN_FRONT_PORT}:80
    depends_on:
      - web

  beanstalk:
    extends:
      file: common-services.yml
      service: beanstalk

  centrifugo:
    extends:
      file: common-services.yml
      service: centrifugo

  redis:
    extends:
      file: common-services.yml
      service: redis

networks:
  default:
    external: true
    name: unitman_default

