version: '3.7'
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-asd@asd.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-asd}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

networks:
  default:
    external: true
    name: unitman_default

