services:
  web:
    extends:
      file: common-services.yml
      service: web
    volumes:
      - '.:/home/containeruser/www'
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
     # - buggregator
      - beanstalk
      - centrifugo
      - postgres
    environment:
      - PHP_OPCACHE_ENABLE=0
      - PHP_OPCACHE_ENABLE_CLI=0
      - PHP_ERROR_REPORTING="E_ALL"
      - PHP_DISPLAY_ERRORS=On
      #- OTEL_SERVICE_NAME=php
      #- OTEL_TRACES_EXPORTER=otlp
      #- OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318
      #- OTEL_PHP_TRACES_PROCESSOR=simple

  postgres:
    extends:
      file: common-services.yml
      service: postgres

  beanstalk:
    extends:
      file: common-services.yml
      service: beanstalk

  centrifugo:
    extends:
      file: common-services.yml
      service: centrifugo

  redis:
    extends:
      file: common-services.yml
      service: redis

  #buggregator:
  #  extends:
  #    file: common-services.yml
  #    service: buggregator

networks:
  default:
    external: true
    name: unitman_default


