version: '3.7'
services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - 5433:5432
    volumes:
      - ./var/volume/pgdata_temporal:/var/lib/postgresql/data

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.23.0
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    ports:
      - 7233:7233

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.23
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.22.3
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_UI_ENABLED=true
    ports:
      - 8088:8080

  web:
    extends:
      file: common-services.yml
      service: web
    volumes:
      - '.:/home/containeruser/www'
    depends_on:
      - temporal
    environment:
      - PHP_OPCACHE_ENABLE=0
      - PHP_OPCACHE_ENABLE_CLI=0
      - PHP_ERROR_REPORTING="E_ALL"
      - PHP_DISPLAY_ERRORS=On
      #- OTEL_SERVICE_NAME=php
      #- OTEL_TRACES_EXPORTER=otlp
      #- OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318
      #- OTEL_PHP_TRACES_PROCESSOR=simple

  elasticsearch:
    extends:
      file: common-services.yml
      service: elasticsearch

  kibana:
    extends:
      file: common-services.yml
      service: kibana

  postgres:
    extends:
      file: common-services.yml
      service: postgres

  unitman-proxy:
    extends:
      file: common-services.yml
      service: unitman-proxy

  #zipkin:
  #  image: openzipkin/zipkin:3
  #  restart: always
  #  ports:
  #    - 9411:9411
  #
  #collector:
  #  container_name: collector
  #  image: otel/opentelemetry-collector-contrib:0.106.1
  #  command: [ "--config=/etc/otel-collector-config.yml" ]
  #  volumes:
  #    - ./.docker/otel/otel-collector-config.yml:/etc/otel-collector-config.yml
  #  ports:
  #    - "4318:4318"
  #    - "4317:4317"

networks:
  default:
    external: true
    name: unitman_default


